grid_map_visualization:
  ros__parameters:
    grid_map_topic: "/height_mapping/local/map"
    grid_map_visualizations:
      - name: "/height_mapping/local/map_cloud"
        type: point_cloud
        params:
          layer: elevation
      - name: "/height_mapping/local/mapping_region"
        type: map_region
        params:
          color: 0xFFFFFF  # white
          line_width: 0.01
